# Generated by Django 5.1.1 on 2024-10-06 06:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlist',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pic'),
            preserve_default=False,
        ),
    ]
