# Generated by Django 5.1.1 on 2024-10-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_mlist_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlist',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
